<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>ServiceDefaults.HealthChecks</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="8.0.2" />
    <PackageReference Include="FastEndpoints" Version="7.0.1" />
  </ItemGroup>

</Project>
